### ISSUE TITLE
Red "anchor" points don't update with text update

### ISSUE THREAD

**Issue by shortword** [e-radionicacom/Inkplate-GUI-Designer#1]
System: Firefox 85 on Windows
Inkplate v6

Steps to reproduce:
1. Start a new UI
2. Create a rectangle with the default dimensions; click "create entity"
3. Use the 'Editing' field on the right to change Cx to 600 and Cy to 400.

Issue:
- The "top right" point stays at (700,100). The bottom left point stays at (100,500)
- This persists even after selecting another object.
- This persists even after a save, reload page, load JSON

![image](https://user-images.githubusercontent.com/4966977/107988876-34d2a480-6fd1-11eb-9092-8900b06cb758.png)

**Comment by nitko12** [comment]
Should be fixed now!

Thanks for pointing the bug out, if you find any other, please let us know!
