### ISSUE TITLE
Text Size in Export Arduino Code

### ISSUE THREAD

**Issue by martindye** [e-radionicacom/Inkplate-GUI-Designer#2]
Currently, when Export Arduino Code is clicked, and there is text on the screen, the text size isn't properly conveyed, here is an example, the size was set to 28px in the editor, but this is ignored and the size is set to "1" instead:

    display.setFont(text2_font);
    display.setTextColor(0, 7);    display.setTextSize(1);    display.setCursor(text2_cursor_x, text2_cursor_y);
    display.print(text2_content);

**Comment by nitko12** [comment]
Text size is always 1, you just change font size accordingly.

Also the displayed size in the font on the web doesn't have to be the same as the text size in Arduino, it would be hard to have all the fonts converted, as that would waste lots of memory if not used correctly, so it's made so that you tweak it yourself.

General rule is that pts used in the Arduino fonts are about 1.5, if I'm not mistaking, pixels in the editor :)

**Comment by martindye** [comment]
That's good to know, it's obvious now!
For positioning fonts and graphics together, trial and error still worked best for me in the end, but the editor was good to get started with. I was modifying the crypto tracker example to use the 3 buttons as a menu to change currency, scale and fiat, and I needed to position the text in a rectangle above each menu button. It needed the font creating in 19pts in the end, to fit the rectangle. The 1.5 rule showed the font slightly smaller than on the designer compared to the actual screen, but was helpful for getting started, example here:

{"widgetCount":0,"primitiveCount":{"pixel":0,"line":0,"circle":0,"rect":1,"triangle":0,"text":2,"bitmap":0},"entities":[{"type":"rect","docs":"https://inkplate.readthedocs.io/en/latest/gui-designer.html#rectangle","id":0,"a":{"x":229,"y":563},"b":{"x":229,"y":600},"c":{"x":311,"y":600},"d":{"x":311,"y":563},"fill":true,"radius":0,"color":0,"modifiers":["a","b","c","d"],"z":0,"editable":{"a":{"type":"coordinate","default":{"x":100,"y":100},"optional":false},"c":{"type":"coordinate","default":{"x":700,"y":500},"optional":false},"color":{"type":"int","min":0,"max":7,"default":0,"optional":false},"fill":{"type":"bool","default":true},"radius":{"type":"int","min":0,"max":800,"default":0,"optional":true}}},{"type":"text","docs":"https://inkplate.readthedocs.io/en/latest/gui-designer.html#text","id":1,"cursor":{"x":230,"y":595},"content":"BTC","font":"FreeSansBold24pt7b","size":"28.5px","color":4,"modifiers":["cursor"],"z":0,"editable":{"cursor":{"type":"coordinate","default":{"x":300,"y":290},"optional":false},"content":{"type":"text","default":"Hello World","optional":false},"font":{"type":"text","default":"FreeSansBold24pt7b","optional":false},"size":{"type":"text","default":"32px","optional":false},"color":{"type":"int","min":0,"max":7,"default":0,"optional":false}}}]}

**Comment by nitko12** [comment]
Awesome, there is a PR opened now also about fonts and sizes, will look into that again :)

I'll close this now, feel free to reopen if you need anything.
