### ISSUE TITLE
Display section not updating after adding anything

### ISSUE THREAD

**Issue by gelse** [e-radionicacom/Inkplate-GUI-Designer#4]
Browsers: both Firefox and Chromium

Reproduction:
- Open the visual editor
- add any widget
from this point on the canvas section does not update any more.

Found exceptions:
- on loading the page, there is a nullref exception in `document.getElementById("imageFile").onchange = ...`
- when adding any other item but the first, there is a `ReferenceError: color is not defined`

**Comment by K-Francis-H** [comment]
Yeah I had the same issue. It looks like the variable `color` isn't defined in any of the drawing functions for Inkplate.js but a function parameter `c` is. So I added this line to the top of each drawing function in Inkplate.js: `let color = c ?? this.color;` . That will correctly use the function param or fallback to the color value defined in the class if `c` is not defined. I'll try and make a pull request as well

**Comment by nitko12** [comment]
Thanks for letting us know, I think I've fixed this now, if it persists please reopen the issue.
